### ISSUE TITLE
Feature request: `values` and `keys` for iterator of values and keys

### ISSUE THREAD

**Issue by ice1000** [mingyli/assoc#1]
I know they're very simple, but it really matters! It can help smooth transition from `BTreeMap` to assoc vec

**Comment by mingyli** [comment]
Yeah adding those methods sounds reasonable. I'm not sure I understand what you mean by smoothing the transition from `BTreeMap` though -- do you have an example?

**Comment by ice1000** [comment]
> Yeah adding those methods sounds reasonable. I'm not sure I understand what you mean by smoothing the transition from `BTreeMap` though -- do you have an example?

So I wanna refactor my code in the following way:

```rust
type BTreeMap<K, V> = Vec<(K, V)>;
```

it would be nice if we can make the rest of the code compile after deleting the import of standard `BTreeMap` and delegate it to assoc array.

**Comment by ice1000** [comment]
Disclaimer: I'm not suggesting _anyone_ to use such a type alias at home. It should be inlined right after that!!

**Comment by mingyli** [comment]
Oh thanks that makes sense. I'll look into this.

**Comment by mingyli** [comment]
@ice1000 do you mind building your project with `assoc` set to the tip of that PR?

**Comment by ice1000** [comment]
@mingyli I _am_ using it to test my project. It's only in the test though, so not uploaded to crates.io
